### ISSUE TITLE
Clicking "Send" on an empty transfer throws an error

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#1031]
To reproduce:
- open a wallet
- click Send

![crash](https://user-images.githubusercontent.com/3758846/192408370-3f2c821d-0607-4c3b-a1bd-1646bad23dca.gif)

**Comment by buberdds** [comment]
I am not exactly sure what are expectations here. Do we really don't want to catch an error when a function input is invalid? Why we even trigger a submit event when a form is empty?
