### ISSUE TITLE
Display version tag in the footer when a tagged version is built

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#1118]
Currently, the build process isn't aware of versioned tags. E.g., even if the built is being made from `v1.3` tag, it will show:
![Screenshot from 2022-10-27 16-58-21](https://user-images.githubusercontent.com/2518544/198328005-1a26aa8f-a394-4e96-86f0-acfbbdd04a1a.png)

It would be nice if we made the build process check if we are currently on a versioned tag and display it appropriately. E.g.:
![Screenshot from 2022-10-27 17-04-18](https://user-images.githubusercontent.com/2518544/198328287-b518414f-21b8-4b32-a1f8-c11d7a8d713a.png)

**Comment by lukaw3d** [comment]
Quick notes:
- if there isn't a tag, probably show the old version
- could use `git describe --exact-match --tags` to print `v1.3`
  or throw `fatal: no tag exactly matches '62737915364f1833e57f832676680ea537ef5320'`
- tag would link to e.g. https://github.com/oasisprotocol/oasis-wallet-web/releases/tag/v1.3
