### ISSUE TITLE
Error desconocido: no se pudo ejecutar 'removeChild' en 'Nodo': el nodo que se eliminará no es un elemento secundario de este nodo.

### ISSUE THREAD

**Issue by JULSANDON** [oasisprotocol/oasis-wallet-web#1354]
Buenas tardes, Disculpar haber si podeis ayudarme. 
he creado hoy mi billeterea por nmemotecnico, y una vez creada, he elegido el la primera direccion, he realizado una pequeña transaccion a modo de prueva, y ahora mismo solo me saca texto el cual pongo en el titulo. 

que deberia hacer para solventarlo y dejar de dar error?

Gracias

**Comment by buberdds** [comment]
Hey, what browser are you using?

**Comment by JULSANDON** [comment]
Google Chrome?

**Comment by JULSANDON** [comment]
Hola, Google Chrome.

**Comment by buberdds** [comment]
Hola, can you provide steps to reproduce this error?

**Comment by lukaw3d** [comment]
Very odd. I suspect some browser extension could be at fault. See if it happens in Incognito mode

**Comment by buberdds** [comment]
Please turn off Chrome translations `chrome://settings/languages` -> Google Translate section -> Use Google Translate
