### ISSUE TITLE
Show "Unlock profile" button if profile available

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-wallet-web#1368]
If you decide to store the keys in your local browser profile, it then shows you a popup to enter password and unlock your profile each time you open the web wallet. This is fine, but if you click "Continue without the profile" button, there is no way to Unlock it afterwards without reloading the page.

In place of the (pointless?) "Close wallet" button the "Unlock profile" button should be shown on the left.

The same issue occurs, if you decide to unlock your profile and then lock it back using the "Lock profile" button. Then the "Close wallet" is also shown which does not make sense.

**Comment by lukaw3d** [comment]
I don't understand this part:
> The same issue occurs, if you decide to unlock your profile and then lock it back using the "Lock profile" button. Then the "Close wallet" is also shown which does not make sense.

After using <kbd>Lock profile</kbd> there's <kbd>Unlock</kbd>, and after that <kbd>Lock profile</kbd> again.

**Comment by matevz** [comment]
> I don't understand this part:
> 
> > The same issue occurs, if you decide to unlock your profile and then lock it back using the "Lock profile" button. Then the "Close wallet" is also shown which does not make sense.
> 
> After using Lock profile there's Unlock, and after that Lock profile again.

I'm getting `Close wallet` after using Lock profile. See below.

![lock-unlock Peek 2023-03-31 17-08](https://user-images.githubusercontent.com/83672/229159170-f5ccd69a-6830-45ee-803f-2a301c4a9d0c.gif)
