### ISSUE TITLE
Create a banner about https://wallet.oasis.io and backport into stable/1.4.x

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#1410]
e.g. "Oasis Wallet has a new home at https://wallet.oasis.io/"

**Comment by lukaw3d** [comment]
| A | B |
| --- | --- |
| ![1](https://user-images.githubusercontent.com/3758846/232845234-5ecb8d1a-d690-4cfc-9b22-2e69f746cc56.png)  |  ![2](https://user-images.githubusercontent.com/3758846/232845247-77b6b23b-5005-455e-93c5-844b02016549.png) |

**Comment by lukaw3d** [comment]
Current URL will redirect to new

**Comment by tjanez** [comment]
I would also vote for option B. It is visually clearer in my view.
