### ISSUE TITLE
Should Transak widget have more contrast in light mode?

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#1456]
| Light | Dark |
| --- | --- |
|  ![wallet stg oasis io_account_oasis1qr3nffx2usjwz2wwmrj35cner5eyrq57ev9729r7_fiat](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/5708c2d9-1da0-4255-81e3-1a539bb284f8) |  ![wallet stg oasis io_account_oasis1qr3nffx2usjwz2wwmrj35cner5eyrq57ev9729r7_fiat (1)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/b88a4d9e-bce9-43b2-b177-a8c73454e05c) |

Some alternatives
| Border | Box center | Box left | Wide |
| --- | --- | --- | --- |
| ![localhost_3000_account_oasis1qqw77q6pzqf9qz0hfadjdfqlh3lkjkpn45u0ewua_fiat](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/3a0b72d5-59eb-4712-a25e-e7a1fb0047c2) | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_fiat (5)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/989e3e51-4329-4feb-958d-6b298fbe42c5)  | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_fiat (3)](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/00594a7c-4b51-4c52-b541-0b35b45fce1d)  | ![localhost_3000_account_oasis1qz78ap0456g2rk7j6rmtvasc9v2kjhz2s58qgj90_fiat](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/a42ec7c2-f450-454f-8d49-5e7b0e41554f) |

@donouwens @tjanez

**Comment by lukaw3d** [comment]
Yes, and make it clearer where the third party content ends

**Comment by tjanez** [comment]
Thanks for the visuals of some alternatives, @lukaw3d!

I like the Box left and Box center variants.

I'm just wondering if it would be possible to somehow "connect" the Transak frame (with the warning banner) with the box above:

> **Buy crypto to your wallet**
>
> This feature allows you to convert your fiat currency into cryptocurrency.

since they belong together logically?

**Comment by tjanez** [comment]
I like the reasoning behind Box center that @donouwens gave. Perhaps we should re-consider wide as well since somehow the Transak widget behaves a bit nicer there (e.g. "Buy now" button is not so far down)?

**Comment by lukaw3d** [comment]
I checked and cut-off for the nicer transak layout is 601px (currently we are using 500px, following their docs)
So we could also have slightly wider Box center
