### ISSUE TITLE
Layout of fatal error is broken

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#1710]
http://localhost:3000/e2e click Trigger fatal saga error
![localhost_3000_e2e](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/9d423f39-e87c-4510-b90b-9f474e2c660a)

From quick check it may have broke in https://github.com/oasisprotocol/oasis-wallet-web/pull/1666

Check if it affects any other components too

**Comment by buberdds** [comment]
yes, switching from div to Grommet Box is causing this issue. Box has overlap issue (mix of flex + min-height and/or wrong/missing flex-shrink). Will look at it.

`https://github.com/oasisprotocol/oasis-wallet-web/pull/1666/commits/951726c6c9ab91c4f8b05146694209f8ab64a270#diff-e52b12bba68e0702881d99f49daf57d5de8ab70c45c6dddcf5e32fb310da95e1R39`
