### ISSUE TITLE
Change Log: Separate tracking of dependency updates

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#1730]
Something to consider for the future:

Should we introduce a separate section and Change Log fragment extension just for Dependency updates?

I think there are many more dependency updates here than in some average Go project.

Also, if we don't want to give too much emphasis on the contents of the dependency updates, the way we only included PR numbers in the Change Logs up to 1.8.0 is a way how to achieve this.

**Comment by lukaw3d** [comment]
I would ignore content and give them all the same fragment message "Dependency updates"

**Comment by buberdds** [comment]
That is my preference as well to group them all together with the same Change Log fragment.
