### ISSUE TITLE
Validator information allows XSS through URLs

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#185]
If validator has a website link `validator.media.website_link = 'javascript:alert(1)'` it executes when user middle-clicks the website link

Minimal code to reproduce:
```jsx
<ValidatorMediaInfo mediaInfo={ { website_link: 'javascript:alert(1)' } } />
```

Blocking https://github.com/oasisprotocol/oasis-wallet-web/issues/181

**Comment by Esya** [comment]
Thanks, fixed in my PR along with a regression test.

**Comment by lukaw3d** [comment]
Oh, if these links come through https://github.com/oasisprotocol/metadata-registry-tools/blob/dc511b52494fd8678c562f0cbbc0a4045b9323ec/registry.go#L116 , they should also already be validated
