### ISSUE TITLE
Received tokens not spendable until reimport

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-wallet-web#1885]
Steps to reproduce:
1. Create a new account
2. Fund the account (Testnet faucet, Transak?, external transaction)
3. Switch to the Home tab and then back to the Wallet tab to refresh the balance so that the **new balance is shown**
4. Try to send the tokens in the Wallet screen, the "Insufficient balance" error is shown
   
   ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/83672/c3beddc2-2e49-48fe-86c7-66d0c05c28c3)

5. Also, if you toggle between the accounts, the old balance is still there in the select dialog
   ![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/83672/c71cc5e3-c3e9-457d-a556-16ce19bf986d)

**Comment by lukaw3d** [comment]
Hm, https://github.com/oasisprotocol/oasis-wallet-web/pull/1692 and its e2e test missed something
