### ISSUE TITLE
Create Profile form validation

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/oasis-wallet-web#1925]
When required form inputs are empty we should show some feedback when user clicks submit button. Currently, nothing happens.  
![Screenshot from 2024-05-08 12-40-03](https://github.com/oasisprotocol/oasis-wallet-web/assets/891392/4e420013-e3e5-409d-82c3-bf58ef7fc13c)

**Comment by lukaw3d** [comment]
Related to https://github.com/oasisprotocol/oasis-wallet-web/pull/1913
https://github.com/oasisprotocol/oasis-wallet-web/blob/545a5f1bba7d24df715d8ca1013335a48f385c8a/src/styles/theme/ThemeProvider.tsx#L278-L286

Without customized colors:
![Peek 2024-05-11 03-17](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/c3a89cc7-f979-4acb-888a-9b732b0973ac)

Or move `required` from CheckBox to FormField and customize the error message:
![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/c66f9921-4da4-4483-852b-247e300d84d2)

**Comment by lukaw3d** [comment]
If checkbox is not wrapped in FormField it also shows focus:
![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/3758846/48bdeed4-b3ec-4943-981a-e630a82ec698)
