### ISSUE TITLE
Select accounts to open modal lacking validation message

### ISSUE THREAD

**Issue by lubej** [oasisprotocol/oasis-wallet-web#1947]
Current state:

Upon clicking "Open", without checking "I understand this password and profile..." I am unable to proceed to next step.

![image](https://github.com/oasisprotocol/oasis-wallet-web/assets/9722540/b798bc92-9c26-4605-84d1-b9b5ad896457)

Proposed solution:

Display some kind of validation message "This field is required", where user would get visual feedback on what steps are necessary to "Open" a wallet.

**Comment by buberdds** [comment]
duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/1925

**Comment by buberdds** [comment]
https://github.com/oasisprotocol/oasis-wallet-web/pull/1936
