### ISSUE TITLE
Issues with footer translations

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#2023]
English variant:
![Screenshot from 2024-07-30 11-48-03](https://github.com/user-attachments/assets/83e35630-c88c-4ba2-9ef6-dc70b43d4484)

Translated variant (e.g. Slovene):
![Screenshot from 2024-07-30 11-47-53](https://github.com/user-attachments/assets/98e140d3-46f3-42df-8e37-98977ee20777)

There are a couple of issues:
1. After version, there is this misrendered text:
```
(<CommitLink />)
```
2. The `built at` part is duplicated (first translated, then in English).
3. The `We’d love your feedback at wallet@oasisprotocol.org` part is not translated. Is just the translation missing or is that text not properly added as a translation string?
4. Some translations are probably outdated and also include text like "Feedback and issues reports are welcome!".

**Comment by lukaw3d** [comment]
"We’d love your feedback at wallet@oasisprotocol.org" is missing translations
