### ISSUE TITLE
Validators table shows "Fee undefined%"

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#235]
https://testnet.oasis-wallet.com/account/oasis1qz62v3qtgfz4uj27e2q9f8lwgjy7vxjtkyx9q436/stake

![image](https://user-images.githubusercontent.com/3758846/130538755-a9905f5f-e8a8-4e86-b169-5837fda62860.png)

**Comment by Esya** [comment]
It seems that oasis-explorer is returning empty commission schedules for all validators...
When not actually changed by the node operator, it used to be 0

https://testnet-api.oasismonitor.com/data/validators

This is not normal behavior - I'll open a ticket there

**Comment by tjanez** [comment]
As was explained in https://github.com/everstake/oasis-explorer/issues/29#issuecomment-919756353, the Oasis Monitor API has replaced the `fee` field in the `data/validators` endpoint with the `commission_schedule` field which has the following structure (example for BinanceStaking):

```
{
    "account_id": "oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm",
    "account_name": "BinanceStaking",

    ... trimmed ...

    "commission_schedule": {
      "rates": [
        {
          "start": 4725,
          "rate": "10000"
        }
      ],
      "bounds": [
        {
          "start": 4725,
          "rate_min": "0",
          "rate_max": "25000"
        }
      ]
    },
    
    ... trimmed ...
    
  },
  ```
 
The wallet needs to be updated for this.
