### ISSUE TITLE
Add expected rewards APY calculation to the wallet staking section

### ISSUE THREAD

**Issue by jacboasis** [oasisprotocol/oasis-wallet-web#244]
The wallet should include some form of a yield calculator, which would be based on the reward schedule, the current epoch, the validator delegating to, amount of tokens and for number of epochs that the tokens will be staked for

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
