### ISSUE TITLE
Testnet/mainnet selection should probably be in stored in URL

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#268]
Otherwise reloading page changes the selection to mainnet

**Comment by csillag** [comment]
What would be an acceptable URL schema?

For example, instead of the current `/account/<address>`, should it be `/account/<network>/<address>` ?

**Comment by lukaw3d** [comment]
I no longer think we want this after https://github.com/oasisprotocol/oasis-wallet-web/issues/792
it would just be a source of conflicting state

**Comment by csillag** [comment]
Indeed.
