### ISSUE TITLE
Error when searching for an address (reading 'sent' of undefined)

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#269]
- open https://wallet.stg.oasisprotocol.org/account/oasis1qqekv2ymgzmd8j2s2u7g0hhc7e77e654kvwqtjwm/stake
- switch to Testnet
- search for `oasis1qz2tg4hsatlxfaf8yut9gxgv8990ujaz4sldgmzx`
- error `Cannot read properties of undefined (reading 'sent')`

**Comment by doorgod42** [comment]
Here's the stacktrace from the console log, when run from chrome in incognito mode (no extensions loaded)
2.68ffbd83.chunk.js:2 TypeError: Cannot read properties of undefined (reading 'sent')
    at nc (main.17701355.chunk.js:1)
    at oi (2.68ffbd83.chunk.js:2)
    at Gu (2.68ffbd83.chunk.js:2)
    at Pc (2.68ffbd83.chunk.js:2)
    at Ec (2.68ffbd83.chunk.js:2)
    at kc (2.68ffbd83.chunk.js:2)
    at yc (2.68ffbd83.chunk.js:2)
    at 2.68ffbd83.chunk.js:2
    at t.unstable_runWithPriority (2.68ffbd83.chunk.js:2)
    at Fo (2.68ffbd83.chunk.js:2)
uu @ 2.68ffbd83.chunk.js:2

**Comment by buberdds** [comment]
Was looking at it and this was resolved by handling unrecognized transaction type  #412

**Comment by pro-wh** [comment]
Oh yeah, this is now rendering successfully

![image](https://user-images.githubusercontent.com/38229038/142269731-1777e76b-877c-48e5-b3af-a9337051f61a.png)

Let's close this out. We can open another issue if there's desire to parse these voting transactions for real.
