### ISSUE TITLE
Hide or blur original mnemonic when confirming it (Firefox)

### ISSUE THREAD

**Issue by matevz** [oasisprotocol/oasis-wallet-web#274]
When clicking *Open my Wallet* you are required to enter specific word from the mnemonic to prove that you really saved it somewhere safe. But currently this doesn't make sense, because the complete mnemonic is visible in the background anyway:
![image](https://user-images.githubusercontent.com/83672/134135282-ae3bb136-c1ca-4e8d-889a-acf73ba04bed.png)

I suggest we blur the original mnemonic in the background when showing the mnemonic confirmation dialog.

**Comment by lukaw3d** [comment]
Firefox users :scream:

**Comment by matevz** [comment]
It seems FF has some performance hickups with the `backdrop-filter` implementation and is currently disabled, but it will be implemented some time in the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1578503

Let's just wait for mozilla folks to fix the issue in the browser and don't mess our code with this. Closing the issue.

**Comment by matevz** [comment]
@lukaw3d thanks for your effort though :wink:

**Comment by tjanez** [comment]
> It seems FF has some performance hickups with the `backdrop-filter` implementation and is currently disabled, but it will be implemented some time in the future: https://bugzilla.mozilla.org/show_bug.cgi?id=1578503

Ok, thanks for researching that.

> Let's just wait for mozilla folks to fix the issue in the browser and don't mess our code with this. Closing the issue.

I disagree. I think it's better to create a work-around. You never know when the upstream issue will be fixed :slightly_smiling_face:.

You can create an issue that will remove the "if firefox then ... else ..." conditional when the upstream issue is solved though.
