### ISSUE TITLE
every visit loads the genesis document

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-web#280]
![image](https://user-images.githubusercontent.com/38229038/134246681-ff071330-ce4f-4547-8011-4e9df2450c96.png)

it's big. any way around this? there's a call to get the chain context alone. several consensus components have their own calls to get the parameters objects.

**Comment by tjanez** [comment]
This also adds unnecessary load on the public gRPC server.

**Comment by tjanez** [comment]
Fixed in #698.
