### ISSUE TITLE
A Fatal Error Occured when search for wallet

### ISSUE THREAD

**Issue by gramanje** [oasisprotocol/oasis-wallet-web#288]
When search for a wallet, stuck on loading and gave the fatal error. Same error also happened when doing nothing.
macOS Catalina - Version 10.15.7
Safari: Version 14.0 (15610.1.28.1.9, 15610)
There are nothing in  developer error/logs section though.

<img width="1189" alt="Screen Shot 2021-09-23 at 01 26 32" src="https://user-images.githubusercontent.com/39063387/134431673-f37bb2de-c635-487d-aee8-c2b6265af415.png">
<img width="1596" alt="Screen Shot 2021-09-23 at 01 26 43" src="https://user-images.githubusercontent.com/39063387/134431692-662909b1-d9ce-4df7-aeb6-a688a15c8f55.png">

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
