### ISSUE TITLE
Fatal error while searching a wallet

### ISSUE THREAD

**Issue by Hagiplox01** [oasisprotocol/oasis-wallet-web#293]
```
Failed to fetch
The above error occurred in task Ja
    created by Za
    created by takeEvery(staking/fetchAccount, Za)
    created by Qa
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Za)
takeEvery(staking/validatorSelected, $a)
TypeError: Failed to fetch
```

**Comment by clicman** [comment]
Same for me while open wallet via Ledger Nano X

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
