### ISSUE TITLE
ledger can't connect in firefox (navigator.usb error)

### ISSUE THREAD

**Issue by joepetrakovich** [oasisprotocol/oasis-wallet-web#299]
I'm unable to open my ledger wallet using the latest firefox.  It works fine in Chrome.

I get a "USB Transport error: navigator.usb is undefined" error.

![ex](https://user-images.githubusercontent.com/5386428/136682869-4bb95552-bebf-45d6-b6ad-b29554cd65e6.png)

**Comment by matevz** [comment]
Mozilla deliberately decided not to implement WebUSB in their browsers because it poses a high security risk. See https://mozilla.github.io/standards-positions/#webusb for details.

**Comment by pro-wh** [comment]
I wouldn't mind having an issue open to track external things around the possibility of Firefox support for Ledger though

**Comment by joepetrakovich** [comment]
Ledger X also has Bluetooth.  Can we support that in Firefox?  They
apparently have APIs.

**Comment by matevz** [comment]
WebUSB and WebHID seem to be on-hold indefinitely for Mozilla developers. Maybe the correct way for Ledger is [WebAuthn](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API)?

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
