### ISSUE TITLE
Add a refresh button to the account list in the selector

### ISSUE THREAD

**Issue by Esya** [oasisprotocol/oasis-wallet-web#35]

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
