### ISSUE TITLE
Improve error when ledger is connected but Oasis app not open

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#376]
If user has ledger open on main menu, and tries to open wallet from ledger:
`Unknown ledger error : Unknown Status Code: undefined`

![Screenshot from 2021-10-31 20-15-00](https://user-images.githubusercontent.com/3758846/139598138-863e2d7b-5deb-41ed-bbb8-1f903246257f.png)

**Comment by pro-wh** [comment]
we're working on improving this here:

https://github.com/oasisprotocol/ledger-js/pull/270/commits/19b4212d79e8beca115e7bcc463913f2495562f0

**Comment by tjanez** [comment]
@lukaw3d, can you re-check if this is still an issue with [@oasisprotocol/ledger 0.2.1](https://www.npmjs.com/package/@oasisprotocol/ledger/v/0.2.1)?

**Comment by lukaw3d** [comment]
> @tjanez : @lukaw3d, can you re-check if this is still an issue with [@oasisprotocol/ledger 0.2.1](https://www.npmjs.com/package/@oasisprotocol/ledger/v/0.2.1)?

- https://wallet.oasisprotocol.org/: `Unknown ledger error : Unknown Status Code: undefined`
- https://wallet.stg.oasisprotocol.org/: `Unknown ledger error : Unknown Status Code: undefined`
- http://localhost:3000/: `Received : "Ledger App Version not supported", this can be a false positive, retry the operation, if the error persists, update the Oasis App on your Ledger.`
   (I have 1.8.2 installed)
   (if I open the app, there's no error)

**Comment by pro-wh** [comment]
>     * (if I open the app, there's no error)

I think I have the same thing, where it doesn't work if you don't have the app open, and I have thought this was normal. didn't know that it comes as an app version issue.

**Comment by pro-wh** [comment]
same behavior on localhost with oasis app 2.3.1 installed

**Comment by pro-wh** [comment]
testing in the ledger-js example directly gives this:

![image](https://user-images.githubusercontent.com/38229038/140237318-3eb0e64e-07d8-4e7a-b545-88f004c69826.png)

from the common.js in that repo:

```js
const ERROR_DESCRIPTION = {
...
  0x6e00: "Oasis app does not seem to be open",
  0x6f00: "Unknown error",
...
};
```

**Comment by pro-wh** [comment]
oh ok the error handling code (error-disregarding, I should say) in `serializePath` is wildly twisting the facts

**Comment by lukaw3d** [comment]
This works well after newest ledger app update without "Pending Ledger review" step
