### ISSUE TITLE
Wallet error - cannot access

### ISSUE THREAD

**Issue by itchgamer** [oasisprotocol/oasis-wallet-web#387]
Hello,

Everytime I try to open my wallet I receive the following error message:

The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by matevz** [comment]
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403
