### ISSUE TITLE
help me recover my stalked wallet

### ISSUE THREAD

**Issue by dmack6945** [oasisprotocol/oasis-wallet-web#388]
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)

**Comment by matevz** [comment]
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403
