### ISSUE TITLE
fatal error opening my wallet

### ISSUE THREAD

**Issue by stressreelief** [oasisprotocol/oasis-wallet-web#389]
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by stressreelief** [comment]
can you please send me an e-mail if this is rectified . I am deeply concerned . Thank you , john 
stressreelief@hotmail.com

**Comment by tendiemanncommeth** [comment]
I got same issue

undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment]
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403
