### ISSUE TITLE
wallet oppening issue

### ISSUE THREAD

**Issue by PabloCumbrera** [oasisprotocol/oasis-wallet-web#401]
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment]
Duplicate of https://github.com/oasisprotocol/oasis-wallet-web/issues/403
