### ISSUE TITLE
me sigue dando error al intentar abrir wuallet

### ISSUE THREAD

**Issue by jota0164** [oasisprotocol/oasis-wallet-web#404]
undefined
The above error occurred in task Za
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
undefined

**Comment by matevz** [comment]
Duplicate of #403

**Comment by jota0164** [comment]
Oki.
Gracias ..sigo a la espera de la activación.
Un saludo
