### ISSUE TITLE
Support for multiple block explorers

### ISSUE THREAD

**Issue by gw0** [oasisprotocol/oasis-wallet-web#407]
The Oasis Wallet currently depends on the external service `oasismonitor.com` (provided by a node operator). Recently, this service went down and this caused a lot of confusion/frustration (see https://github.com/oasisprotocol/oasis-wallet-web/issues/403).

To prevent such issues other wallets typically support multiple block explorers and let the user choose which one to use. I suggest that the Oasis Wallet should support at least 2 block explorer services.

**Comment by tjanez** [comment]
Superseded by https://github.com/oasisprotocol/oasis-wallet-web/issues/693, implemented in https://github.com/oasisprotocol/oasis-wallet-web/pull/704.

Note that the backend choice is not exposed to the users but added as a build time option for wallet operators.
