### ISSUE TITLE
Error when opening a wallet from mnemonic

### ISSUE THREAD

**Issue by zsh065400** [oasisprotocol/oasis-wallet-web#416]
Http response at 400 or 500 level
The above error occurred in task Cn
    created by Dn
    created by takeEvery(wallet/openWalletFromMnemonic, Dn)
    created by En
Tasks cancelled due to error:
takeEvery(wallet/openWalletFromMnemonic, Dn)
Dn
Dn
takeEvery(wallet/openWalletFromPrivateKey, Yn)
takeEvery(wallet/openWalletsFromLedger, In)
takeEvery(wallet/addWallet, Tn)
Bn
takeEvery(wallet/fetchWallet, Ln)
takeLatest(wallet/selectWallet, Fn)
takeEvery(wallet/closeWallet, Rn)
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1047878)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1070696)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1069926)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056709)
    at Be (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056515)
    at xt (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064004)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064785)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065726)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065705)

**Comment by lukaw3d** [comment]
"task Cn" seems to be getBalance 
https://github.com/oasisprotocol/oasis-wallet-web/blob/a144e9cc22b2844413751bc5ad351dc47a76904f/src/app/state/wallet/saga.ts#L53-L72

---
<br><br><br><br>



Dn is minified openWalletFromMnemonic:
```js
          function Dn(e) {
              var t, n, a, r, c, o, i, s;
              return Q.a.wrap((function(l) {
                  for (;;) switch (l.prev = l.next) {
                      case 0:
                          return t = e.payload, l.delegateYield(Object(re.b)(X.hdkey.HDKey.getAccountSigner, t), "t0", 2);
                      case 2:
                          return n = l.t0, a = Object(ee.h)(n.secretKey), r = zt.a.Mnemonic, c = n.publicKey, o = Object(ee.h)(c), l.delegateYield(Object(re.b)(ee.d, c), "t1", 8);
                      case 8:
                          return i = l.t1, l.delegateYield(Object(re.b)(Cn, c), "t2", 10);
                      case 10:
                          return s = l.t2, l.delegateYield(Object(re.d)(qn.addWallet({
                              id: _n++,
                              address: i,
                              publicKey: o,
```

openWalletFromMnemonic source:
https://github.com/oasisprotocol/oasis-wallet-web/blob/8021aa546a1b1eeb40b2745ec1df74f97889c90a/src/app/state/wallet/saga.ts#L119-L133

**Comment by lukaw3d** [comment]
Probably related to https://github.com/oasisprotocol/oasis-wallet-web/issues/428

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
