### ISSUE TITLE
error con mi ledger

### ISSUE THREAD

**Issue by sergiorodca** [oasisprotocol/oasis-wallet-web#427]
The device was disconnected.
The above error occurred in task Et
    created by takeEvery(ledger/enumerateAccounts, Et)
    created by At
Tasks cancelled due to error:
takeEvery(ledger/enumerateAccounts, Et)
undefined

**Comment by pro-wh** [comment]
Have you been able to get your Ledger reconnected?

Thanks for adding this to our knowledgebase.

I don't have any actionable ideas for changes to the web wallet regarding this though.

**Comment by Cadmeos** [comment]
I somehow managed to get my ledger connected after Ctrl + f5. But that mainly happened when I yet didn't have an oasis wallet address on my ledger. Now I can easily access it using the oasis chrome extension.

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
