### ISSUE TITLE
cant access new created wallet

### ISSUE THREAD

**Issue by portefeuille-nano** [oasisprotocol/oasis-wallet-web#428]
Http response at 400 or 500 level
The above error occurred in task Ja
    created by Xa
    created by Xa
    created by takeEvery(staking/fetchAccount, Xa)
    created by er
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, Xa)
takeEvery(staking/validatorSelected, Qa)
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1047878)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1070696)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1069926)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056709)
    at Be (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056515)
    at xt (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064004)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064785)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065726)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065705)

**Comment by pro-wh** [comment]
Devs, is there any way to restore the stack trace here? All I can go by is the "fetchAccount" in there, which at least narrows things down.

This particular error message is characteristic of grpc-web, btw. That means it has to do with a non-block-explorer call.

**Comment by lukaw3d** [comment]
@pro-wh I built 7094119a10c9bbc1119a371cd2110d9ef2127630, put build/static/js/2.c809311d.chunk.js (not exactly 2.7533b3a7.chunk.js) through beautifier.io, and found
```js
          function er() {
              return Q.a.wrap((function(e) {
                  for (;;) switch (e.prev = e.next) {
                      case 0:
                          return e.delegateYield(Object(re.h)(ar.fetchAccount, Xa), "t0", 1); // <---
                      case 1:
                          return e.delegateYield(Object(re.h)(ar.validatorSelected, Qa), "t1", 2);
                      case 2:
```
```js
          function Xa(e) {
              var t, n, a, r, c;
              return Q.a.wrap((function(o) {
                  for (;;) switch (o.prev = o.next) {
                      case 0:
                          return t = e.payload, o.delegateYield(Object(re.d)(ar.setLoading(!0)), "t0", 2);
                      case 2:
                          return o.delegateYield(Object(re.b)(ee.a, t), "t1", 3);
                      case 3:
                          return n = o.t1, o.delegateYield(Object(re.b)(Za), "t2", 5);
                      case 5:
                          return o.delegateYield(Object(re.a)({
                              delegations: Object(re.b)(Ja, n), // <---
                              debondingDelegations: Object(re.b)($a, n)
                          }), "t3", 6);
                      case 6:
                          return a = o.t3, r = a.delegations, c = a.debondingDelegations, o.delegateYield(Object(re.d)(ar.updateDelegations(r)), "t4", 10);
                      case 10:
```

So error occurred in task Ja === loadDelegations: 
https://github.com/oasisprotocol/oasis-wallet-web/blob/0b4e36dad0fce0228d00fa872e21994caca7319f/src/app/state/staking/saga.ts#L171
https://github.com/oasisprotocol/oasis-wallet-web/blob/0b4e36dad0fce0228d00fa872e21994caca7319f/src/app/state/staking/saga.ts#L49-L60

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
