### ISSUE TITLE
A fatal unexpected error has occurred and Oasis-wallet must stop. Please copy report this issue below on our github account. You can also try refreshing page to see if the issue persists. Once you leave this page, all of your wallets will be closed.

### ISSUE THREAD

**Issue by jdwk1510** [oasisprotocol/oasis-wallet-web#439]
Http response at 400 or 500 level
The above error occurred in task lt
    created by takeEvery(network/selectNetwork, lt)
    created by dt
Tasks cancelled due to error:
takeEvery(network/selectNetwork, lt)
D@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1047882
Ft@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1070701
https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1069928
Ue@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056713
Be@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1056517
xt@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064006
Tt@https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1064787
https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065728
https://wallet.oasisprotocol.org/static/js/2.7533b3a7.chunk.js:2:1065706
[native code]

**Comment by pro-wh** [comment]
Cross referencing #428, where I'm also asking if we can restore a stack trace like this

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
