### ISSUE TITLE
Feature idea: different URL for wallets you own

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-web#440]
@buberdds suggests:

> The problem is that current main wallet url handles different app states one for a default preview and one for selected wallet and selected wallet requires opening a wallet first. Maybe app need a different url for selected wallet where in a case of missing wallet user would go through "Open wallet" step?

Thanks for the additional analysis on this. I'll take this into account if we get into discussing a larger rework of this. Using a different URL for users' wallets is something we'll consider. I wonder if we might alternatively try to unify more of the functionality actually to reduce the differences though. It should only come down to whether or not you can sign transactions, after all.

_Originally posted by @pro-wh in https://github.com/oasisprotocol/oasis-wallet-web/issues/419#issuecomment-967738323_

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
