### ISSUE TITLE
Error when accessing Oasis Web wallet

### ISSUE THREAD

**Issue by vakgadde** [oasisprotocol/oasis-wallet-web#447]
Http response at 400 or 500 level
The above error occurred in task ft
    created by takeEvery(network/selectNetwork, ft)
    created by ht
Tasks cancelled due to error:
takeEvery(network/selectNetwork, ft)
D@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1047878
Ft@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1070696
Ut/<@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1069926
Ue@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056709
Be@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056515
xt@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064004
Tt@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064785
r.W@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065728
r.R@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065705

**Comment by pro-wh** [comment]
Cross referencing #428, where I'm also asking if we can restore a stack trace like this

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
