### ISSUE TITLE
Ledger error

### ISSUE THREAD

**Issue by Cadmeos** [oasisprotocol/oasis-wallet-web#448]
The device was disconnected.
The above error occurred in task Tt
    created by takeEvery(ledger/enumerateAccounts, Tt)
    created by Lt
Tasks cancelled due to error:
takeEvery(ledger/enumerateAccounts, Tt)
undefined

**Comment by pro-wh** [comment]
cross reference: #427 for an error with the same top-level message

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
