### ISSUE TITLE
Ledger error with web wallet

### ISSUE THREAD

**Issue by TrojanGhost** [oasisprotocol/oasis-wallet-web#449]
Can not open Ledger with web wallet. Just keeps looping saying "Opening Ledger through USB" but nothing happens.

**Comment by pro-wh** [comment]
Does this ledger device work with other software?

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
