### ISSUE TITLE
Fatal Error same as others 

### ISSUE THREAD

**Issue by zephzeph** [oasisprotocol/oasis-wallet-web#479]
NetworkError when attempting to fetch resource.
The above error occurred in task vr
    created by vr
    created by takeEvery(account/fetchAccount, vr)
    created by xr
Tasks cancelled due to error:
takeEvery(account/fetchAccount, vr)
Or

**Comment by matevz** [comment]
Oasis monitor was down yesterday. Duplicate of #403. Reopen, if error still persists today please.
