### ISSUE TITLE
I can't open my wallet from the nano S ledger.

### ISSUE THREAD

**Issue by wixpo** [oasisprotocol/oasis-wallet-web#490]
I can't open my wallet from the nano S ledger. I put the ledger in Oasis ready and I get an error.

The device was disconnected.
The above error occurred in task Tt
    created by takeEvery(ledger/enumerateAccounts, Tt)
    created by Lt
Tasks cancelled due to error:
takeEvery(ledger/enumerateAccounts, Tt)
undefined

**Comment by matevz** [comment]
Which browser are you using? There has been some issues with Firefox and Ledger recently.

**Comment by wixpo** [comment]
Google Chrome

**Comment by wixpo** [comment]
Even now to do staking I can't do it from the ledger either. Error: Ledger publickey: undefined Unknown Status Code Undefined

**Comment by wixpo** [comment]
Now I see that I need to close Ledger live. Now is working
