### ISSUE TITLE
UI breaks after expanding a validator quickly after reload

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#501]
- open https://wallet.oasisprotocol.org/account/oasis1qq3xrq0urs8qcffhvmhfhz4p0mu7ewc8rscnlwxe/stake
- open console and simulate slower network `Network Throttling: Fast 3G`
- reload page
- quickly click `Staking Fund` (before GetEpoch request?)
- UI disappears

![Peek 2021-12-01 06-55](https://user-images.githubusercontent.com/3758846/144179745-e320cd20-c935-44ad-afc5-b583b86d5866.gif)

**Comment by lukaw3d** [comment]
@matevz  Seems to be caused because props are readonly, and sort mutates original array
https://github.com/oasisprotocol/oasis-wallet-web/blob/e994b39d61e9362af7f30a7f27651fbc7862ec01/src/app/pages/StakingPage/Features/CommissionBounds/index.tsx#L54-L59

**Comment by lukaw3d** [comment]
if I add `.slice()` to clone array before, there's no error but:

| click quickly after reload | click slowly after reload |
| --- | --- |
|  ![Screenshot from 2021-12-01 07-30-14](https://user-images.githubusercontent.com/3758846/144184406-509bd126-ed1a-4cd0-99a1-86a3ed29aca8.png)  |  ![Screenshot from 2021-12-01 07-30-26](https://user-images.githubusercontent.com/3758846/144184413-5c2fb3be-b938-4caf-b811-dd22740cd847.png) |

**Comment by matevz** [comment]
I can't seem to reproduce this. Are there issues with oasis monitor again?

**Comment by kinqsta** [comment]
I just have same problem

```
Http response at 400 or 500 level
The above error occurred in task ft
    created by takeEvery(network/selectNetwork, ft)
    created by ht
Tasks cancelled due to error:
takeEvery(network/selectNetwork, ft)
D@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1047878
Ft@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1070696
Ut/<@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1069926
Ue@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056709
Be@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056515
xt@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064004
Tt@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064785
r.W@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065728
r.R@https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065705

```

**Comment by lukaw3d** [comment]
@kinqsta That looks like a different problem

**Comment by lukaw3d** [comment]
> @matevz  I can't seem to reproduce this

Hm, I can't reproduce now either

**Comment by lukaw3d** [comment]
Reproduced again by enabling `Network Throttling: Fast 3G`. Adding to description.

**Comment by matevz** [comment]
> Reproduced again by enabling `Network Throttling: Fast 3G`. Adding to description.

Does it depend on the browser and incognito mode?

**Comment by lukaw3d** [comment]
Nope, reproduced in normal Chrome and Firefox

**Comment by Boi4155** [comment]
I am able to reproduce this bug in any browser with or without extensions. I dont believe enabling Network Throttling: Fast 3G or running normally makes a difference on this bug.
<img width="1070" alt="error" src="https://user-images.githubusercontent.com/93211952/150646297-62d75cd0-d155-40b8-98fa-f2a97b2d7c03.png">
I am an end user so It is difficult for me to debug when every variable and function is called Fi,Di,Li,Si. But it looks like the same bug error as posted before.
In my case specifically I cannot open info on the 'WePiggy Staking' validator. It is impossible for me to debond from them now. until this is fixed.
Another detail I dont know if matters or not is that the 'WePiggy Staking' is in between two other validators. I.e. it shows up in the middle for the UI.
Waiting an 'x' amount for time for 'y' to load makes no difference either it seems.
Please look into this, or offer an alternative to debonding as for now it is impossible. Thanks

**Comment by matevz** [comment]
@Boi4155 Can you check the Network tab if there are any failed requests? Maybe the oasismonitor was down for a moment and wallet couldn't connect to it?

**Comment by Boi4155** [comment]
I found nothing to do with failed requests there
Here's a video, although it is pretty much the same as the top one

https://user-images.githubusercontent.com/93211952/150904287-942fa8be-7f64-4867-a60a-94bc4077204d.mp4
