### ISSUE TITLE
Add a way to reclaim all escrow shares

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-wallet-web#503]
Because the web wallet converts from ROSE when determining how many tokens to withdraw, it is possible to be left with a delegation that is worth an infinitesimally small amount of ROSE.  As the amount delegated is less than a share, no rewards are generated, and this spams the account with 0 token staking rewards, as well as leaving a worthless delegation stuck in the metadata.

The web wallet badly needs a way to reclaim all shares, that actually fully reclaims everything.

**Comment by matevz** [comment]
This is actually duplicate of #492 :wink:
