### ISSUE TITLE
No acepta mis 24 palabras

### ISSUE THREAD

**Issue by Tadeo2022** [oasisprotocol/oasis-wallet-web#513]
Hola mi nombre es Tadeo y soy nuevo en esta comunidad, tengo un problema grave ; no puedo ingresar a mi wallet porque esta no acepta mis 23 palabras clave y ya la ingrese muchas veces, así que les dejo el código de error que me tira a ver si me pueden ayudar y muchísimas gracias. 

Http response at 400 or 500 level
The above error occurred in task ft
    created by takeEvery(network/selectNetwork, ft)
    created by ht
Tasks cancelled due to error:
takeEvery(network/selectNetwork, ft)
Error: Http response at 400 or 500 level
    at new D (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1047878)
    at Ft (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1070696)
    at _t.<anonymous> (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1069926)
    at Ue (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056709)
    at Be (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1056515)
    at xt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064004)
    at Tt (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1064785)
    at _t.r.W (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065726)
    at _t.r.R (https://wallet.oasisprotocol.org/static/js/2.48cea8b1.chunk.js:2:1065705)

**Comment by Tadeo2022** [comment]
Estoy muy preocupado pues tengo miedo de no poder ingresar más a mi wallet, lo que seria muy gracioso porque es la primera cuenta que me hago con esta wallet, o sea solo pude ingresar una vez sola, deposite mis criptomonedas rose y no pude ingresar más, también es muy triste aparte de gracioso porque perdería las criptomonedas, si me ayudan se los agradecería mucho. , gracias.

**Comment by lukaw3d** [comment]
Hm `Http response at 400 or 500 level`

Maybe just try again. (But you do need 24 words, not 23)

**Comment by Tadeo2022** [comment]
Si 24 , me equivoque al escribir aqui...🤷‍♂️

**Comment by Tadeo2022** [comment]
Me esta volviendo loco!😔
Invalid keyphrase. Please make sure to input the words in the right order, all lowercase.

**Comment by Tadeo2022** [comment]
Seguramente fue un error de la plataforma Oasis porque estoy viendo que a mi me dieron 25 palabras no 24, y las de arriba no coinciden con las de abajo, les mando capturas, total ya las doy por perdidas las cripto😔😕☹
![Screenshot_20211202-193916_Chrome](https://user-images.githubusercontent.com/95452028/144579720-3f4194a9-320f-4c2d-8624-8b722c624156.jpg)
![Screenshot_20211202-193752_Chrome](https://user-images.githubusercontent.com/95452028/144579728-ba8e5c64-0946-4bba-aa45-6dfe2233a90a.jpg)

**Comment by lukaw3d** [comment]
That's strange. You had already entered valid mnemonic last time, if you got to `Http response at 400 or 500 level`

**Comment by lukaw3d** [comment]
From your screenshots it looks like you Google Translated the mnemonic :O that mnemonic won't work

You could try translating back to English, but I'm not completely sure it will work; only Google Translate has your original mnemonic in server logs

**Comment by lukaw3d** [comment]
Can you create a new wallet for yourself and paste your address here?

- Open https://wallet.oasisprotocol.org/create-wallet without Google Translate
- Safely write down the generated mnemonic. Don't throw it away.
- Open https://wallet.oasisprotocol.org/open-wallet/mnemonic and type your new mnemonic
- Copy paste your address oasis1..

**Comment by lukaw3d** [comment]
I might have a solution. Here is mnemonic dictionary Google Translated to Spanish, so you can reverse it:
https://pastebin.com/61sk914e

**Comment by lukaw3d** [comment]
@Tadeo2022 Any success?
