### ISSUE TITLE
does not accept my 24 keywords

### ISSUE THREAD

**Issue by RonaldBuen** [oasisprotocol/oasis-wallet-web#519]
hello my name is Ronald, just today I created the account in oasis wallet successfully, I did all the process to be able to participate in the yuzu swap, I sent to the wallet 10,000 Rose, then I was trying by all means to enter with my 24 keywords but they don't work, I need help so that everything goes well and not lose my 10,000 Rose, 

 thanks in advance.

**Comment by lukaw3d** [comment]
- Can you confirm the error you see is: `Invalid keyphrase. Please make sure to input the words in the right order, all lowercase.`
- Enter your 24 words separated by spaces, not newlines
- Does your browser detect any spelling mistakes? 
  ![image](https://user-images.githubusercontent.com/3758846/144532819-ce7a59c4-1417-4a73-a56b-2e357145629b.png)
- Oasis Wallet uses the English dictionary of words defined by BIP39 https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt. Check that your words appear on the list

**Comment by RonaldBuen** [comment]
Gracias por tu colaboración. 

1. Ese es el error que me presenta al ingresar las keyphrases. (Invalid keyphrase. Please make sure to input the words in the right order, all lowercase.)

2. Acabo de verificar y efectivamente hay 4 palabras en mi mnemonic que no aparecen en el diccionario que referencias (https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt ). En ese caso cómo se procede?
 
Agradezco enormemente cualquier información que me puedas suministrar.

**Comment by lukaw3d** [comment]
You should probably just try to find similar words on the list, instead of those 4

**Comment by Tadeo2022** [comment]
Tengo el mismo problema!!!☹

**Comment by RonaldBuen** [comment]
> Probablemente debería intentar encontrar palabras similares en la lista, en lugar de esas 4

Buen dia, de las 4 palabras que no aparecen solo 3 tenia una parecida, intente con esas mas la palabra que no tiene una similar y aun no me permite , me lanza el mismo error 
(Frase clave no válida. Asegúrese de ingresar las palabras en el orden correcto, todas en minúsculas.)

**Comment by Tadeo2022** [comment]
Si yo revise la la lista y estan todas las palabras mias, las traduci al ingles a ver si era ese el problema y nada y ahora que hacemos,? Por lo menos no estamos solos en el sufrimiento😂😔😭

**Comment by lukaw3d** [comment]
@RonaldBuen I don't think there's any official way to help if one of your words is not correct.

There are some mnemonic recovery tools (like https://3rditeration.github.io/mnemonic-recovery/src/index.html and https://lukaw3d.github.io/find-missing-word-in-mnemonic/) to find a missing word, but I don't know if any are safe to use.

**Comment by lukaw3d** [comment]
@RonaldBuen Were you using Google Translate, and wrote down your mnemonic in Spanish? If so, here is mnemonic dictionary Google Translated to Spanish, so you can reverse it:
https://gist.github.com/lukaw3d/0a8b7df88766dd408a4dbcbefef4677f
