### ISSUE TITLE
Ledger Nano issue with Oasis web wallet

### ISSUE THREAD

**Issue by blokeharry** [oasisprotocol/oasis-wallet-web#536]
Hi,

I originally created oasis wallet on my Ledger Nano S to stake ROSE tokens through anthem portal.
Since Anthem is deprecated, I am trying to access my existing Oasis wallet on my Ledger Nano S through Oasis Web Wallet interface.
But not able to do so. I have go following different errors. Please advise how to fix this issue.

My firmware version on Ledger Nano S device is 2.1.0 My Ledger Live version is 2.36.2 and Oasis app version on Ledger is 1.8.2.

Error 1)
Received : "Ledger App Version not supported", this can be a false positive, retry the operation, if the error persists, update the Oasis App on your Ledger.

Error 2)
Unknown error : A transfer error has occurred.

Error 3)
The device was disconnected.
The above error occurred in task Tt
    created by takeEvery(ledger/enumerateAccounts, Tt)
    created by Lt
Tasks cancelled due to error:
takeEvery(ledger/enumerateAccounts, Tt)
undefined

**Comment by pro-wh** [comment]
I can only suggest to try a different USB port on your computer or to try a different USB cable.

**Comment by blokeharry** [comment]
Actually, after multiple attempts changing USB ports and plugging in and
out the usb cable, I was able to successfully access my ledger oasis
Wallet. Thank you for your response!

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
