### ISSUE TITLE
Wallet problem, token disappear?

### ISSUE THREAD

**Issue by underratedpro** [oasisprotocol/oasis-wallet-web#546]
I've made a new wallet for rose token and I send there some and the problem is I cannot see them because they just disappear after few days. There is no any transaction of withdraw them, only i can see is previous transaction when I added them. so why my balance is 0? what i can do with tha? help me please

![rose](https://user-images.githubusercontent.com/96841175/147694004-6adad50d-9677-4a38-b371-ef3bc634df44.png)
.

**Comment by underratedpro** [comment]
ok. omg after seconds i posted they just appeard thanks

**Comment by underratedpro** [comment]
sometimes they are there smetime they arnt can you explain why is that happening? i m waiting for my ledger if i put them tehere is it safer?

**Comment by pro-wh** [comment]
one thing it could be: those totals come from a block explorer, and that may take some time to sync with recent transactions on chain

**Comment by underratedpro** [comment]
thank you it explain me everything :P

**Comment by 28041972** [comment]
buenas tardes pro-wh me llamo pedro habri una billetera oasis1qqqk9g9kepejk7lcl8d7slm5cwlzjnjync5vxaqc hice un ingreso de 659.9rose cerre la billetera y al poner mi frase semilla me abre con esta direccion oasis1qz3p6k363e4a7c2k0uzwrzrzr54d2u6ua56fnd6p y un saldo 0rose estoy desesperado me puedes ayudar por favor muchas gracias.

**Comment by pro-wh** [comment]
@28041972 could you check if that problem is the same as described here https://github.com/oasisprotocol/oasis-wallet-web/issues/491#issuecomment-982693221 and move discussion there? we're looking for information on how to reproduce that behavior

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.

**Comment by 28041972** [comment]
Buenas tardes GASPER muchas gracias por el mensaje lo voy a intentar está
tarde y te comentaré si me ha funcionado gracias por preocuparte,avia dado
por perdido mis fondos.pero sigo creyendo en el proyecto y estoy acumulando
Rose  cada día más y más.
