### ISSUE TITLE
Make it more obvious that PEM keys can be used to open a wallet

### ISSUE THREAD

**Issue by Esya** [oasisprotocol/oasis-wallet-web#55]
We currently support opening wallets with the ED255159 PEM files, maybe make it more obvious that the whole envelope can be copy pasted, or add a file input to locally load the file from disk

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
