### ISSUE TITLE
Local env issue with validators endpoint

### ISSUE THREAD

**Issue by buberdds** [oasisprotocol/oasis-wallet-web#561]
Hey, when I work with the app locally `validators` endpoint always fails.  

url: `http://localhost:9001/data/validators?limit=500`
response code: `Status Code: 500 Internal Server Error`
response: `json: unsupported value: NaN` 

How can I fix that? Thanks!

**Comment by pro-wh** [comment]
Is there maybe a way to get more diagnostic info from the explorer container?

**Comment by buberdds** [comment]
I don't see anything interesting in container's logs. I will just mock that response for now. Anyway, thanks!
