### ISSUE TITLE
Accessing more than 5 addresses when using Ledger

### ISSUE THREAD

**Issue by npinto** [oasisprotocol/oasis-wallet-web#562]
Hello,

I'm trying to access index 0 to 5 on my Ledger using the web wallet or the chrome extension but it's not showing them up. Would it be possible to add this functionality ? That is to add more than 5 addresses, with e.g. a next page option ?

Thanks for your help and Happy New Year!
Best,
Nico

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
