### ISSUE TITLE
Warn if user tries to transfer to validator

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#567]
e.g. "This is a validator wallet address. Transfers to this address does not stake your funds with the validator. Are you sure you want to continue?"

Motivation: A lot of people seem to be transferring ROSE to validators. (and Binance keeps saying they don't control Binance Staking, so they can't reverse it)

Related: https://github.com/oasisprotocol/oasis-wallet-ext/issues/217

**Comment by Trinkolin** [comment]
I've lost my roses - am I suppose to kill myself now because the wallet was not synchro with the site ?

**Comment by Trinkolin** [comment]
I wanna kill myself for trusting the chrome plugin wallet. Thanks.

**Comment by Trinkolin** [comment]
So my only solution because you could not handle correctly the validators is to really kill myself ... Thanks.

**Comment by lukaw3d** [comment]
Fixed in https://github.com/oasisprotocol/oasis-wallet-web/pull/576
