### ISSUE TITLE
Unable to load validators when staking

### ISSUE THREAD

**Issue by ReddropAsh** [oasisprotocol/oasis-wallet-web#572]
After opening the wallet the stake tab displays

Validators

Couldn't load transactions. List may be empty or out of date. Error: request https://monitor.oasis.dev/data/validators?limit=500 status 500

Unable to manage staking

**Comment by pro-wh** [comment]
I've filed an issue for a potential cause

https://github.com/everstake/oasis-explorer/issues/33

**Comment by kjniedz** [comment]
I've been experiencing a similar issue this morning with the staking tab, unable to manage staking / can't load transactions. 

Error: https://monitor.oasis.dev/data/validators?limit=500 status 500

json: unsupported value: NaN

**Comment by k-bailey** [comment]
same issue here

**Comment by oiolor** [comment]
so do i

**Comment by Ryannguyen1993** [comment]
Same issue here! Couldn't load delegations and stake.

**Comment by danen-carlson** [comment]
Same Issue here.

**Comment by liorpinsky** [comment]
same issue. anyone knows how to resolve this?

**Comment by matevz** [comment]
Oasis monitor was up and down in the last days. Duplicate of #403. We are working on this.
