### ISSUE TITLE
Validators can't load transactions. Error: status 500

### ISSUE THREAD

**Issue by kjniedz** [oasisprotocol/oasis-wallet-web#573]
<img width="1781" alt="Screen Shot 2022-01-08 at 11 22 41 AM" src="https://user-images.githubusercontent.com/45904241/148651864-741a596b-26fe-49c1-aeb5-4fb3a4cc9bbd.png">
<img width="1556" alt="Screen Shot 2022-01-08 at 11 23 03 AM" src="https://user-images.githubusercontent.com/45904241/148651868-1fed7cfc-985d-46fc-baf0-1abf28e0abf9.png">
Validators

"Couldn't load transactions. List may be empty or out of date. 

Error: request https://monitor.oasis.dev/data/validators?limit=500 status 500

There are no records to display"

On the Active Validators tab, it shows the red 'X' for inactive staking, as well as an unknown fee / validator. Unable to manage my current Oasis staking.

**Comment by levineel42** [comment]
I am dealing with this same problem, it is very frustrating

**Comment by levineel42** [comment]
If anybody knows what to do that would be awesome

**Comment by levineel42** [comment]
I am surprised that such an advanced protocol is dealing with these problems... early stages but definitely not a great sign...

**Comment by pro-wh** [comment]
let's unify this with #572
