### ISSUE TITLE
Unable to stake coins using oasis wallet

### ISSUE THREAD

**Issue by karlr1965** [oasisprotocol/oasis-wallet-web#574]
Hi I am new to this and made a wallet Friday and transfered some Rose to it. When I try to stake it give an error message and does not show any staking choices. Is this already a known error and is there a work around?

**Comment by pro-wh** [comment]
let's unify this with #572

**Comment by matevz** [comment]
Oasis monitor was up and down in the last days. Duplicate of #403. We are working on this.
