### ISSUE TITLE
Error acces oasis wallet

### ISSUE THREAD

**Issue by MrJay1977** [oasisprotocol/oasis-wallet-web#603]
![IMG_20220120_124743](https://user-images.githubusercontent.com/98094540/150333571-1f0dbb11-2374-405f-9491-af9d9a15848a.jpg)

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
