### ISSUE TITLE
Error when selecting the following delegator: WePiggy Staking

### ISSUE THREAD

**Issue by ylimeam** [oasisprotocol/oasis-wallet-web#613]
I would like to transfer my tokens out of the following delegator: WePiggy Staking, however every time I click on the name it takes me to a blank page and I am kicked out of my wallet (as shown in the video, I get taken out to the following URL that doesn't load https://wallet.oasisprotocol.org/account/oasis1qz23vch5ah2gxx0lt048nlp03swvvu9q0care53a/active-delegations). This issue is not prevalent when I select other delegators.

https://user-images.githubusercontent.com/98562413/151459565-c8906050-bd35-4420-a2fb-7423ba208cdb.mp4

Can someone please explain what is happening?

**Comment by pro-wh** [comment]
thanks for the detailed report! let's see if #611 fixes this

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
