### ISSUE TITLE
A fatal error has occurred and Oasis Wallet must stop

### ISSUE THREAD

**Issue by airdrops-id** [oasisprotocol/oasis-wallet-web#623]
Error: Http response at 400 or 500 level

The above error occurred in task loadDelegations
    created by fetchAccount
    created by fetchAccount
    created by takeEvery(staking/fetchAccount, fetchAccount)
    created by stakingSaga
Tasks cancelled due to error:
takeEvery(staking/fetchAccount, fetchAccount)
takeEvery(staking/validatorSelected, getValidatorDetails)

E@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:94905:13
Y@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96430:33
X/<@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96404:25
Ib@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95551:22
O@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:95537:5
wc@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96058:21
yc@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96125:11
n.W@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96070:5
n.R@https://wallet.oasisprotocol.org/static/js/2.cd0bb50b.chunk.js:96066:59

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
