### ISSUE TITLE
Couldn’t load validators 

### ISSUE THREAD

**Issue by djack99587** [oasisprotocol/oasis-wallet-web#624]
Whenever I goto stake section of wallet I get message saying “ couldn’t load validators list may be empty or out of date “ error request

**Comment by ylimeam** [comment]
I'm having the same issue

<img width="1784" alt="Screen Shot 2022-02-19 at 12 10 40 PM" src="https://user-images.githubusercontent.com/98562413/154813470-61c827ca-8608-47c8-bc07-14eec9cb6d12.png">

**Comment by seatrips** [comment]
Couldn't load validators. List may be empty or out of date. Error: request https://monitor.oasis.dev/data/validators?limit=500 status 500

SAME FOR ME

**Comment by seatrips** [comment]
https://www.oasisscan.com/validators should be the link i guess

**Comment by djack99587** [comment]
Thank you for the list ! How do you delegate if it won’t come up in the wallet ?

**Comment by erlinichen** [comment]
![image](https://user-images.githubusercontent.com/86234741/154954921-2d721a35-795b-4f09-8927-93eafdd3f04f.png)

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
