### ISSUE TITLE
Support multiple block explorer backends

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#693]
Abstract the block explorer API queries and add support for multiple block explorer backends.

Add support for [Oasis Scan's block explorer API](https://github.com/bitcat365/oasisscan-backend).

Add support for choosing/configuring the block explorer backend at wallet's build or deploy time.

**Comment by lukaw3d** [comment]
Progress in https://github.com/oasisprotocol/oasis-wallet-web/tree/oasisscan

- oasismonitor's getAccount:
  - [x] extract usage
  - [x] add typescript binding for oasisscan
  - [x] parse into reusable format
- oasismonitor's getValidatorsList:
  - [x] extract usage
  - [x] add typescript binding for oasisscan
  - [x] parse into reusable format
- oasismonitor's getTransactionsList:
  - [ ] extract usage
  - [x] add typescript binding for oasisscan
  - [ ] parse into reusable format
- [x] add oasisscan's URLs to config, selectable with env at build time
- [ ] find replacement for https://grpc.oasis.dev/oasis-core.Staking/DelegationInfosFor
