### ISSUE TITLE
CSP Blocks Loading Validator List & Tx List with connect-src Error

### ISSUE THREAD

**Issue by memoriesadrift** [oasisprotocol/oasis-wallet-web#721]
Upon trying to open the validator list or tx history, I receive the following error: 
`Content Security Policy: The page’s settings blocked the loading of a resource at https://api.oasisscan.com/mainnet/validator/list?pageSize=500 (“connect-src”).` or the same error for the tx history, containing the address in the query.

**This is all not the case in development, running the app locally displays all data correctly.**
Upon further testing in local development the validator list stopped working but with a different error - I get an error 500, while all other data displays correctly.
I also tested the RPC calls via Postman and the correct responses were returned.

**Comment by tjanez** [comment]
Thanks for the report, @memoriesadrift.

Indeed, the CSP has not been properly updated when we redeployed the wallet. It should be fixed now.
