### ISSUE TITLE
Account  error 

### ISSUE THREAD

**Issue by Gwenael11** [oasisprotocol/oasis-wallet-web#722]
Hi all,

oasis1 qrjq emlv vya4 9gw7 32jw ypn4 cxc3 ksla y5um v944
When opening my wallet on the web, I get error messages for weeks now:

Recent ones
Impossible de charger le compte. Des informations peuvent être manquantes ou obsolètes. TypeError: Failed to fetch
Impossible de charger les transactions. La liste peut être vide ou obsolète. TypeError: Failed to fetch

I can see that the tokens are there, but no possibility to access staking nor to operate any operation.

Any idea how to solve / bypass this?

Thanks in advance !

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
