### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by guncuha** [oasisprotocol/oasis-wallet-web#723]
Hello, my wallet is oasis1qzrdek8xzuuauxkwn93hd6kxuw0zt834xcd7ftm9. When i open my wallet i see 2 errors. 1st:"Couldn't load account. Information may be missing or out of date. TypeError: Failed to fetch". 2nd:"Couldn't load transactions. List may be empty or out of date. TypeError: Failed to fetch". When i go to staking i see this: "Couldn't load validators. List may be empty or out of date. TypeError: Failed to fetch". And the last error i have is that i cant see some on my coins which i transfered to my oasis wallet a couple of days ago. Please help me

**Comment by jimmyg272727** [comment]
I'm having the same issue.. I can't open my validator and access those coins.. Getting the same failed to fetch errors as above??

**Comment by guncuha** [comment]
Thanks for the quick fix, guys

**Comment by guncuha** [comment]
> I'm having the same issue.. I can't open my validator and access those coins.. Getting the same failed to fetch errors as above??

Write a post like this, they fixed my problem today

**Comment by jimmyg272727** [comment]
Ok thank you 


Sent from Yahoo Mail for iPhone


On Tuesday, March 1, 2022, 2:20 PM, guncuha ***@***.***> wrote:





I'm having the same issue.. I can't open my validator and access those coins.. Getting the same failed to fetch errors as above??


Write a post like this, they fixed my problem today

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
