### ISSUE TITLE
Add info about block explorer backed being used

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#724]
Now that we have support for the 2 block explorer backends, namely Oasis Scan and Oasis Monitor, it would be nice to show which one is used.

Could we add an icon somewhere or text like "Powered by Oasis Scan"/"Powered by Oasis Monitor"  in the footer?

I guess for "Powered by Oasis Monitor" it could be even more precise, i.e. "Powered by Oasis Monitor & SimplyVC's gRPC endpoint", after #705.

**Comment by buberdds** [comment]
Does that work for you?
<img width="673" alt="Screenshot 2022-03-07 at 10 06 30" src="https://user-images.githubusercontent.com/891392/157000885-cb7d94e3-d143-493c-856e-e9a0acd8177c.png">
