### ISSUE TITLE
i can't create my walet

### ISSUE THREAD

**Issue by hamanhtoan** [oasisprotocol/oasis-wallet-web#728]
Hello,
i can't create my wallet. when i entered my keyphrase, it's correct but it said "Invalid keyphrase. Please make sure to input the words in the right order, all lowercase"
i don't know why. Could you check it?

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
