### ISSUE TITLE
Worst wallet ever !!!!!!!!   

### ISSUE THREAD

**Issue by djack99587** [oasisprotocol/oasis-wallet-web#730]
Everyday something new not working with this wallet . Now I can’t get into my wallet at all . Cannot access web wallet or chrome extension, no balance is coming up but it’s showing on oasis monitor so I know my account is fine  . Cannot access my funds when I need them this is crazy !

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
