### ISSUE TITLE
Reorder validators to encourage decentralization

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#766]
- Naive implementation: randomize on refresh. Order is different every time
- Better UX: save randomization seed. Order is different on every computer/browser
- Use quality metrics: uptime, fee, escrow, self-delegation

**Comment by pro-wh** [comment]
> save randomization seed

should make sure it's somehow stable when validators are added/removed. e.g., it wouldn't work well to do this:

1. sort by id
2. shuffle using a random seed

possibly better:

1. for each validator, calculate `randomScore = PRF(key = persistedSeed, id)`
2. sort by randomScore

**Comment by Yawning** [comment]
I think the last time this was discussed, partitioning the validators into buckets by voting power and shuffling inside the buckets was brought up.

As an alternative, clearly indicating to the users (eg: by darkening the top-N validators) that they should try to delegate to the smaller validators (a la Terra?  I don't remember which system did this), to increase voting power diversity, should probably ALSO be done.
