### ISSUE TITLE
Does "Hot reloadable translation" work with parceljs

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#777]
Does this still work, and is this still needed after https://github.com/oasisprotocol/oasis-wallet-web/pull/743

https://github.com/oasisprotocol/oasis-wallet-web/blob/e9c5ac7d392e55a709e4d730b5fc1384d8fa2bfa/src/index.tsx#L60-L65

**Comment by buberdds** [comment]
It does work and this this code is not longer necessary, will create PR in a sec.
