### ISSUE TITLE
When backend doesn't give a response, prefer showing ? (for unknown)

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#816]
Currently, backend API calls fallback to returning 0 which could mislead/deceive users (e.g. when showing balances).

For example:
https://github.com/oasisprotocol/oasis-wallet-web/blob/e13653153ddb86d0d441d59e4a8589f776e1d928/src/app/pages/AccountPage/index.tsx#L86

Prefer returning `?` (another option would be `N/A`, but that is perhaps less international?).

**Comment by pro-wh** [comment]
ugh does this originate from aggressive golang omit_empty stuff? or does the backend sometimes return nullish for accounts that have nonzero general balance?

in the grpc API, the general balance being absent really does mean zero

**Comment by lukaw3d** [comment]
No, it happens when API requests fail

Example screenshot after #916 after getting delegations from oasisscan fails and from gRPC fails
![after](https://user-images.githubusercontent.com/3758846/177891093-905f3939-0f97-4899-ac9d-f4258f183902.png)

**Comment by pro-wh** [comment]
ah ok
