### ISSUE TITLE
Add ability to open additional accounts for the same wallet / mnemonic

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-web#82]
Besides the _primary account_ (described in [ADR 0008](https://github.com/oasisprotocol/oasis-core/blob/master/docs/adr/0008-standard-account-key-generation.md#key-derivation-paths)), also allow opening additional accounts for non-zero key numbers, i.e. `m/44'/474'/1'`, `m/44'/474'/2'`, ...

**Comment by Esya** [comment]
Makes sense for it to work with non-ledger wallets too - this implies a good bit of refactoring though - tagging this as a post-release feature https://github.com/Esya/oasis-wallet/milestone/2
