### ISSUE TITLE
Configurable number of Ledger wallets

### ISSUE THREAD

**Issue by gw0** [oasisprotocol/oasis-wallet-web#826]
Currently, when using a Ledger device with the Oasis Web Wallet the screen "Select the wallets to open" only shows the first 5 wallets to open (by derivation path).

Power users will likely want to use more than 5 wallets per Ledger device. Possible solutions:

- Configurable number of Ledger wallets (hidden under an "Advanced" tab or menu)
- Option to manually specify derivation paths to import.
- Iterative retrieving of Ledger wallets until it finds e.g. 2 empty/never-used wallets.

The library seems to support a `count` parameter that is set by default to 5:
- https://github.com/oasisprotocol/oasis-wallet-web/blob/e13653153ddb86d0d441d59e4a8589f776e1d928/src/app/lib/ledger.ts#L37

**Comment by lukaw3d** [comment]
We probably want pagination or specifying paths, because listing accounts from ledger is so slow:
- ledger s: 5 accounts: 6429 ms
- ledger x: 5 accounts: 2560 ms

**Comment by lukaw3d** [comment]
Fixed by https://github.com/oasisprotocol/oasis-wallet-web/pull/1124

**Comment by gw0** [comment]
Woohoo, awesome! :)
