### ISSUE TITLE
With my Mnemonic is oppened other wallet

### ISSUE THREAD

**Issue by jlarreamiguel** [oasisprotocol/oasis-wallet-web#827]
I have written my Mnemonic and it has not been oppened my wallet, but other without founds. Please I need help to solve this

**Comment by pro-wh** [comment]
how did you get the first wallet? is there any evidence that the first one was associated with the mnemonic?

report seems the same as #491

**Comment by jlarreamiguel** [comment]
I got the first wallet as ussual I think from oasis protocol. I can see the first wallet by the link and I see the funds, but when I want to oppen the wallet in order to make transactions, I writte the Mnemonic and another wallet is oppened with different adress and without funds.
I do not know what to do. how is possible this has happened?
Many thanks

**Comment by pro-wh** [comment]
can you perform these steps with a newly generated wallet and get this same wrong-account behavior? it would help if you could post a video of that, if you're able to reproduce this behavior
