### ISSUE TITLE
Combine `start` and `start:ext`

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#828]
If we want a single `start` command for both web and ext we would need to:
- combine `.parcelrc` and `.parcelrc-ext` configs
- combine `ext-dev` and `ext-prod` targets
- restructure folders so that built folder has `/manifest.json`, `/_locales`, and `/oasis-xu-frame.html` on root

_Originally posted by @lukaw3d in https://github.com/oasisprotocol/oasis-wallet-web/pull/805#discussion_r871595122_

**Comment by pro-wh** [comment]
what's the context of this? do we want to unify them?

**Comment by lukaw3d** [comment]
After https://github.com/oasisprotocol/oasis-wallet-web/pull/805 we will have `yarn start` for serving web and `yarn start:ext` for serving extension. Running both is more annoying, slower, and potentially breaks .parcel-cache.

So I'd like to use parcel-bundler's option to serve multiple targets
