### ISSUE TITLE
Support the burn transaction

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-wallet-web#837]
There is an explicit burn tx type that, although likely currently totally unused, is useful in certain situations.  This should be exposed and available as a wallet operation.

**Comment by csillag** [comment]
The OasisScan API is returning wrong data about the burns in the transaction list. ( See here: https://github.com/bitcat365/oasisscan-backend/issues/5 ) Until that is fixed, we can only show these transactions with the Oasis Monitor backend.
