### ISSUE TITLE
Change the designator in transaction history

### ISSUE THREAD

**Issue by Esya** [oasisprotocol/oasis-wallet-web#89]
Change `Validator` and `To` to `Account` to avoid misleading issues inside TransactionHistory

**Comment by tjanez** [comment]
> Change `Validator` and `To` to `Account` to avoid misleading issues inside TransactionHistory

Perhaps it would be even better to not use the generic term `Account` but use the transaction's context to display a more meaningful thing.

For example, for a transfer txn where the wallet is the destination or for a reclaim escrow transaction, it would show `From`.

On the other had, for a transfer txn where the wallet is the source or for a add escrow transaction, it would show `To`.

I would also be nice if it would be unified with the Preview transaction's field names (#77).

**Comment by gparty** [comment]
Thank you for reporting this issue. We have updated our Oasis Wallet with bug fixes and new features which should also solve mentioned issue above.

If you still encounter same or similar issue, please check our [FAQ](https://docs.oasis.dev/general/manage-tokens/faq) or send an email to our support team at wallet@oasisprotocol.org.
