### ISSUE TITLE
Loading spinner is malformed in extension layout

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-web#967]
Probably caused by "Loading account" splitting into two lines, and modal width being narrow
![image](https://user-images.githubusercontent.com/3758846/184244479-ce9f8412-1799-45e3-a07c-76684dd91df2.png)

**Comment by buberdds** [comment]
Fixed in Grommet repo https://github.com/grommet/grommet/pull/6277

**Comment by tjanez** [comment]
We need to wait for a new upstream Gromet release.

**Comment by lukaw3d** [comment]
Nice!
