### ISSUE TITLE
"A fatal error occurred" when opening the website

### ISSUE THREAD

**Issue by mohammed-najib** [oasisprotocol/oasis-wallet-web#991]
Http response at 400 or 500 level
The above error occurred in task st
    created by takeEvery(network/selectNetwork, st)
    created by lt
Tasks cancelled due to error:
takeEvery(network/selectNetwork, st)
undefined

the above error occurred when simply trying to open web page "https://testnet.oasis-wallet.com/"

**Comment by gparty** [comment]
Hi @mohammed-najib,

Please be careful. Our official Oasis Wallet -  Web can be found at https://wallet.oasisprotocol.org/. Then you can switch between mainnet and testnet.

**Comment by tjanez** [comment]
https://testnet.oasis-wallet.com/ -> now redirects to https://wallet.oasisprotocol.org/

**Comment by pro-wh** [comment]
> https://testnet.oasis-wallet.com/ now redirects to https://wallet.oasisprotocol.org/



did oasis take control of the domain? or is that only an observation of what an external domain is doing right now?

**Comment by tjanez** [comment]
> did oasis take control of the domain? or is that only an observation of what an external domain is doing right now?

Thanks for the remark. The oasis-wallet.com domain has been transferred to the Oasis Foundation and we set up the redirect. So, indeed, Oasis Foundation controls the domain.
